permissions: write-all
name: Production Build and Package
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Run composer & install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: latest
          args: --ignore-platform-reqs

      - name: Dump autoload
        uses: php-actions/composer@v6
        with:
          php_version: latest
          args: --ignore-platform-reqs
          command: dump-autoload -oa

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install 

      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build 

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: production-build
          path: "./"
